### ISSUE TITLE
Legacy image fails to start

### ISSUE THREAD

**Issue by jjbubudi** [gliderlabs/docker-consul#94]
Command: `docker run progrium/consul -server -bootstrap`

Keep getting the error `Error response from daemon: Cannot start container: [8] System error: no such file or directory`

Image ID: `bde95fb7344a`

**Comment by mklatsky** [comment]
I âme running into the same error.

**Comment by tmichaud314** [comment]
+1

**Comment by robbrockbank** [comment]
+1

**Comment by MatthewRDodds** [comment]
Confirmed as an issue for both `consul-0.4` and `consul-0.3` as well.

**Comment by progrium** [comment]
So there's a number of problems here. First, Docker Hub rebuilds all tags when anything happens. So images on Docker Hub are not exactly immutable, otherwise this would Just Work. 

The problem seems to be with opkg packages, which as of recently install just fine but then don't work. The entrypoint for this container is a script run with bash, installed from opkg. 

Now I have no idea what's going on with opkg or the openwrt package repository. It's never been terribly reliable. However, I *should* be able to change the legecy branch to use alpine and everything should work as normal. So I'm going to try that unless anybody has updates on how to fix the opkg package issue.

**Comment by tmichaud314** [comment]
This might be related: https://dev.openwrt.org/ticket/19893

**Comment by progrium** [comment]
Okay, legacy was patched to use alpine and installs packages that are known to work. This doesn't look good for `progrium/busybox`, but since alpine is what the new docker-consul images are based on we should be fine going forward. There *are* some interesting quirks with DNS resolution in the libc Alpine uses, so report any of those issues separately.

**Comment by progrium** [comment]
Can anybody confirm that it works?

**Comment by rozaliev** [comment]
Yes, it seems to be working ok, thank you for the fix!

**Comment by tmichaud314** [comment]
So far so good for me as well, thanks for the quick resolve!

**Comment by robbrockbank** [comment]
Looks good - thanks!

**Comment by mklatsky** [comment]
Excellent- thanks for the quick response !

**Comment by progrium** [comment]
Okay, if you run into issues related to musl quirks (keep an eye out for DNS related issues in particular) submit a separate issue.

**Comment by jjbubudi** [comment]
Thanks for the quick response!
